pipeline {
    agent any {
    stages {
        stage('CHECKOUT') {
            steps {
               git branch: 'master', changelog: false, poll: false, url: 'https://github.com/akshu2430/simple-node-js-react-npm-app.git'
            }
        }
        
       stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
